### YamlMime:ManagedReference
items:
- uid: System.IdentityModel.Services.AsynchronousOperationException
  id: AsynchronousOperationException
  children:
  - System.IdentityModel.Services.AsynchronousOperationException.#ctor
  - System.IdentityModel.Services.AsynchronousOperationException.#ctor(System.Exception)
  - System.IdentityModel.Services.AsynchronousOperationException.#ctor(System.String)
  - System.IdentityModel.Services.AsynchronousOperationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.IdentityModel.Services.AsynchronousOperationException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: AsynchronousOperationException
  nameWithType: AsynchronousOperationException
  fullName: System.IdentityModel.Services.AsynchronousOperationException
  type: Class
  summary: "Unntaket oppstod når det oppstår en feil under en asynkron operasjon."
  syntax:
    content: 'public class AsynchronousOperationException : Exception'
  inheritance:
  - System.Exception
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.IdentityModel.Services.AsynchronousOperationException.#ctor
  id: '#ctor'
  parent: System.IdentityModel.Services.AsynchronousOperationException
  langs:
  - csharp
  name: AsynchronousOperationException()
  nameWithType: AsynchronousOperationException.AsynchronousOperationException()
  fullName: System.IdentityModel.Services.AsynchronousOperationException.AsynchronousOperationException()
  type: Constructor
  assemblies:
  - System.IdentityModel.Services
  namespace: System.IdentityModel.Services
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.IdentityModel.Services.AsynchronousOperationException&quot;> </xref> klasse."
  remarks: "Denne konstruktøren initialiserer den <xref:SystemException.Message>for den nye forekomsten til en system-angitt melding som beskriver problemet.</xref:SystemException.Message> Meldingen tar hensyn til den gjeldende kulturen i systemet.       Tabellen nedenfor viser første egenskapsverdiene for den nye forekomsten.      | Egenskapen | Verdien |   |--------------|-----------|   | <xref:System.Exception.InnerException>| `null`.|   | <xref:System.Exception.Message>| Lokaliserte feil melding strengen. |</xref:System.Exception.Message> </xref:System.Exception.InnerException>"
  syntax:
    content: public AsynchronousOperationException ();
    parameters: []
  overload: System.IdentityModel.Services.AsynchronousOperationException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Services.AsynchronousOperationException.#ctor(System.Exception)
  id: '#ctor(System.Exception)'
  parent: System.IdentityModel.Services.AsynchronousOperationException
  langs:
  - csharp
  name: AsynchronousOperationException(Exception)
  nameWithType: AsynchronousOperationException.AsynchronousOperationException(Exception)
  fullName: System.IdentityModel.Services.AsynchronousOperationException.AsynchronousOperationException(Exception)
  type: Constructor
  assemblies:
  - System.IdentityModel.Services
  namespace: System.IdentityModel.Services
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.IdentityModel.Services.AsynchronousOperationException&quot;> </xref> klassen med en system-angitt feilmelding og en referanse til det interne unntaket er årsaken til dette unntaket."
  remarks: "Et unntak som er registrert som en direkte resultatet av et tidligere unntak må inkludere en referanse til det tidligere unntaket i den <xref:System.Exception.InnerException>egenskapen.</xref:System.Exception.InnerException> Den <xref:System.Exception.InnerException>egenskapen returnerer den samme verdien som er sendt til konstruktøren.</xref:System.Exception.InnerException>       Tabellen nedenfor viser første egenskapsverdiene for den nye forekomsten.      | Egenskapen | Verdien |   |--------------|-----------|   | <xref:System.Exception.InnerException>| Referansen for det indre unntaket. |   | <xref:System.Exception.Message>| En system-angitt melding som beskriver problemet.</xref:System.Exception.Message> </xref:System.Exception.InnerException> Meldingen tar hensyn til gjeldende system kultur. |"
  syntax:
    content: public AsynchronousOperationException (Exception innerException);
    parameters:
    - id: innerException
      type: System.Exception
      description: "Den <xref:System.Exception>som er årsaken til den gjeldende unntaket.</xref:System.Exception> Hvis den `innerException` -parameteren er ikke <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>, oppstår det gjeldende unntaket i en <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref> blokken som behandler det interne unntaket."
  overload: System.IdentityModel.Services.AsynchronousOperationException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Services.AsynchronousOperationException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.IdentityModel.Services.AsynchronousOperationException
  langs:
  - csharp
  name: AsynchronousOperationException(String)
  nameWithType: AsynchronousOperationException.AsynchronousOperationException(String)
  fullName: System.IdentityModel.Services.AsynchronousOperationException.AsynchronousOperationException(String)
  type: Constructor
  assemblies:
  - System.IdentityModel.Services
  namespace: System.IdentityModel.Services
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.IdentityModel.Services.AsynchronousOperationException&quot;> </xref> klassen med en angitt feilmelding."
  remarks: "Denne konstruktøren initialiserer den <xref:System.Exception.Message>for den nye unntak ved hjelp av den `message` parameteren.</xref:System.Exception.Message> Innholdet i `message` er ment å forstå av mennesker. Oppkalleren for denne konstruktøren kreves for å sikre at denne strengen er lokalisert for den gjeldende kulturen i systemet.       Tabellen nedenfor viser første egenskapsverdiene for den nye forekomsten.      | Egenskapen | Verdien |   |--------------|-----------|   | <xref:System.Exception.InnerException>| `null`.|   | <xref:System.Exception.Message>| Feil melding strengen. |</xref:System.Exception.Message> </xref:System.Exception.InnerException>"
  syntax:
    content: public AsynchronousOperationException (string message);
    parameters:
    - id: message
      type: System.String
      description: "Feilmelding som forklarer hvorfor unntaket."
  overload: System.IdentityModel.Services.AsynchronousOperationException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Services.AsynchronousOperationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.IdentityModel.Services.AsynchronousOperationException
  langs:
  - csharp
  name: AsynchronousOperationException(SerializationInfo,StreamingContext)
  nameWithType: AsynchronousOperationException.AsynchronousOperationException(SerializationInfo,StreamingContext)
  fullName: System.IdentityModel.Services.AsynchronousOperationException.AsynchronousOperationException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.IdentityModel.Services
  namespace: System.IdentityModel.Services
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.IdentityModel.Services.AsynchronousOperationException&quot;> </xref> klasse serialiserte dataene."
  remarks: "Denne konstruktøren kalles under deserialisering til reconstitute unntak objektet overføres via en dataflyt."
  syntax:
    content: protected AsynchronousOperationException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "En <xref href=&quot;System.Runtime.Serialization.SerializationInfo&quot;> </xref> objekt som har datatypen serialiserte objektet."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "En <xref:System.Runtime.Serialization.StreamingContext>objekt som inneholder kontekstavhengig informasjon om kilden eller målet.</xref:System.Runtime.Serialization.StreamingContext>"
  overload: System.IdentityModel.Services.AsynchronousOperationException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Services.AsynchronousOperationException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.IdentityModel.Services.AsynchronousOperationException
  langs:
  - csharp
  name: AsynchronousOperationException(String,Exception)
  nameWithType: AsynchronousOperationException.AsynchronousOperationException(String,Exception)
  fullName: System.IdentityModel.Services.AsynchronousOperationException.AsynchronousOperationException(String,Exception)
  type: Constructor
  assemblies:
  - System.IdentityModel.Services
  namespace: System.IdentityModel.Services
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.IdentityModel.Services.AsynchronousOperationException&quot;> </xref> klassen med en angitt feilmelding og en referanse til det interne unntaket er årsaken til dette unntaket."
  remarks: "Et unntak som er registrert som en direkte resultatet av et tidligere unntak må inkludere en referanse til det tidligere unntaket i den <xref:System.Exception.InnerException>egenskapen.</xref:System.Exception.InnerException> Den <xref:System.Exception.InnerException>egenskapen returnerer den samme verdien som er sendt til konstruktøren.</xref:System.Exception.InnerException>       Tabellen nedenfor viser første egenskapsverdiene for den nye forekomsten.      | Egenskapen | Verdien |   |--------------|-----------|   | <xref:System.Exception.InnerException>| Referansen for det indre unntaket. |   | <xref:System.Exception.Message>| Feil melding strengen. |</xref:System.Exception.Message> </xref:System.Exception.InnerException>"
  syntax:
    content: public AsynchronousOperationException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "Feilmelding som forklarer hvorfor unntaket."
    - id: innerException
      type: System.Exception
      description: "Den <xref:System.Exception>som er årsaken til den gjeldende unntaket.</xref:System.Exception> Hvis den `innerException` -parameteren er ikke <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>, oppstår det gjeldende unntaket i en <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref> blokken som behandler det interne unntaket."
  overload: System.IdentityModel.Services.AsynchronousOperationException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Exception
  isExternal: false
  name: System.Exception
- uid: System.IdentityModel.Services.AsynchronousOperationException.#ctor
  parent: System.IdentityModel.Services.AsynchronousOperationException
  isExternal: false
  name: AsynchronousOperationException()
  nameWithType: AsynchronousOperationException.AsynchronousOperationException()
  fullName: System.IdentityModel.Services.AsynchronousOperationException.AsynchronousOperationException()
- uid: System.IdentityModel.Services.AsynchronousOperationException.#ctor(System.Exception)
  parent: System.IdentityModel.Services.AsynchronousOperationException
  isExternal: false
  name: AsynchronousOperationException(Exception)
  nameWithType: AsynchronousOperationException.AsynchronousOperationException(Exception)
  fullName: System.IdentityModel.Services.AsynchronousOperationException.AsynchronousOperationException(Exception)
- uid: System.IdentityModel.Services.AsynchronousOperationException.#ctor(System.String)
  parent: System.IdentityModel.Services.AsynchronousOperationException
  isExternal: false
  name: AsynchronousOperationException(String)
  nameWithType: AsynchronousOperationException.AsynchronousOperationException(String)
  fullName: System.IdentityModel.Services.AsynchronousOperationException.AsynchronousOperationException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.IdentityModel.Services.AsynchronousOperationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.IdentityModel.Services.AsynchronousOperationException
  isExternal: false
  name: AsynchronousOperationException(SerializationInfo,StreamingContext)
  nameWithType: AsynchronousOperationException.AsynchronousOperationException(SerializationInfo,StreamingContext)
  fullName: System.IdentityModel.Services.AsynchronousOperationException.AsynchronousOperationException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.IdentityModel.Services.AsynchronousOperationException.#ctor(System.String,System.Exception)
  parent: System.IdentityModel.Services.AsynchronousOperationException
  isExternal: false
  name: AsynchronousOperationException(String,Exception)
  nameWithType: AsynchronousOperationException.AsynchronousOperationException(String,Exception)
  fullName: System.IdentityModel.Services.AsynchronousOperationException.AsynchronousOperationException(String,Exception)
- uid: System.IdentityModel.Services.AsynchronousOperationException.#ctor*
  parent: System.IdentityModel.Services.AsynchronousOperationException
  isExternal: false
  name: AsynchronousOperationException
  nameWithType: AsynchronousOperationException.AsynchronousOperationException
